### ISSUE TITLE
Prompt shows up in diff file when changing the hostname

### ISSUE THREAD

**Issue by remoteur** [supertylerc/ansible-netmiko-stdlib#10]
Hey,

If I load a config file that changes the device hostname the prompt name containing the new hostname shows up in the diff file. 

Example:
This is the conf file, I load it to a device that's got 'router' set as hostname:
cat /tmp/config 
hostname smth

Here's the diff file:
http://fpaste.org/201232/42706641/

**Comment by supertylerc** [comment]
@remoteur thanks for the report.  I suspect this is an issue in Netmiko.  I'll do some testing this week to verify and submit a PR to fix it.
