### ISSUE TITLE
Save Configuration

### ISSUE THREAD

**Issue by supertylerc** [supertylerc/ansible-netmiko-stdlib#2]
This module currently modifies the active (running) configuration but does not save it.  The module should add a new parameter to save the active configuration to the startup configuration.  The default should be `True`.

**Comment by spirrello** [comment]
Hi,

Is the save configuration feature intended to assist Netmiko in saving the running config of a Cisco IOS device?

**Comment by supertylerc** [comment]
@spirrello:

The save configuration feature would allow the Ansible module to copy the running config to the startup config for any supported platform.

Unfortunately, I don't have the time to put toward this at this time.
